### ISSUE TITLE
Live Simulator: 2 integration

### ISSUE THREAD

**Issue by MikuAuahDark** [LeNitrous/sukufes-icon-builder#3]
Someone send me link to this repository, and since I'm thinking of built-in icon builder in my [Live Simulator](https://github.com/MikuAuahDark/livesim2) which is also written in LOVE. Can I integrate this to my Live Simulator: 2 so I don't need to create new one?

**Comment by LeNitrous** [comment]
Sorry for not replying so soon! I've been really busy for the last few weeks. Also sure, feel free to integrate it to your Live Simulator! It might need some refinement because for some reason LOVE lowers the quality a bit. Just fork it and you're set. All of the libraries and source files are included in this repository.
